name: Linux Snapcraft Build

on:
  push:
    branches:
      - dev

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies 
      run: | 
        sudo apt-get update sudo apt-get install -y libudev1

    - name: Build Snap
      env: 
        TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }} 
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      uses: snapcore/action-build@v1
      id: snapcraft

    - name: List project directory 
      run: ls -lh

    - name: Upload Snap artifact
      uses: actions/upload-artifact@v4
      with:
        name: hyperionbox-linux-snap
        path: ./*.snap
