name: Linux Snap Build

on:
  push:
    branches:
      - dev

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        rm -rf src-tauri/target/release/bundle/deb/*.deb
        sudo apt-get update
        sudo apt-get install -y \
          snapd \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          pkg-config \
          build-essential \
          curl \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          gstreamer1.0-vaapi
        sudo snap install snapcraft --classic

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Rust
      run: |
        rustup default stable
        rustup target add x86_64-unknown-linux-gnu
        rustup target add aarch64-unknown-linux-gnu

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: 'src-tauri -> src-tauri/target'

    - name: Export Tauri signing environment variables
      shell: bash
      run: |
        echo "TAURI_SIGNING_PRIVATE_KEY=${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "TAURI_SIGNING_PRIVATE_KEY_PASSWORD=${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: bun install

    - name: Build Linux Deb
      run: |
        if [ "${{ matrix.arch }}" = "amd64" ]; then
          bun tauri build --bundles deb --target x86_64-unknown-linux-gnu
        else
          bun tauri build --bundles deb --target aarch64-unknown-linux-gnu
        fi

    - name: Build Snap package
      run: |
        sudo snapcraft pack --destructive-mode --target-arch=${{ matrix.arch }}

    - name: Upload Snap artifact
      uses: actions/upload-artifact@v4
      with:
        name: hyperionbox-linux-snap-${{ matrix.arch }}
        path: ./*.snap
